odrive.core.drive.clientId=426a51bf-2a99-4ab9-94ab-1d130c7555b7
odrive.core.drive.redirectUri.port=8783
odrive.core.drive.redirectUri.context=/odrive
odrive.core.drive.redirectUri=http://127.0.0.1:${odrive.core.drive.redirectUri.port}${odrive.core.drive.redirectUri.context}